## HPC Model Quality Review

This section evaluates all model runs in `models/hpc_runs` and compares them consistently.

Flow:
1. Build one shared evaluation data plan (top cell below).
2. Run one evaluation cell per model folder (or reuse existing results if a model type is not supported by `load_checkpoint`).
3. Compare all available `eval_results.json` files with `compare_eval`.

### Helpers

In [108]:
from pathlib import Path
import json
import os
import numpy as np
import yaml
import pandas as pd
from evaluation.compare_models import PhasedModelComparator

try:
    from tabulate import tabulate as _tabulate
except Exception:
    _tabulate = None

PROJECT_ROOT = Path('/Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data').resolve()
HPC_RUNS_DIR = PROJECT_ROOT / 'models' / 'hpc_runs'
HPC_RUNS_DIR_PHASED = PROJECT_ROOT / "models" / "hpc_runs" / "3-phase"
COMPARISON_OUTPUT_DIR = PROJECT_ROOT / 'evaluation_comparison_hpc_runs'
COMPARISON_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

os.chdir(PROJECT_ROOT)

def _discover_model_dirs_in(base_dir: Path) -> list[Path]:
    model_dirs = []

    if not base_dir.exists():
        print(f"Directory does not exist: {base_dir}")
        return model_dirs

    for d in sorted(base_dir.iterdir()):
        if not d.is_dir() or d.name == "UserProfiles":
            continue

        if _ranked_eval_json(d).exists() or _aggregated_eval_json(d).exists():
            model_dirs.append(d)

    return model_dirs

_CANONICAL_METRIC_BY_KEY = {
    'reconstructionrmse': 'Reconstruction RMSE',
    'reconstructionmse': 'Reconstruction MSE',
    'reconstructionloglikelihood': 'Reconstruction Log-Likelihood',
    'reconstructionlog-likelihood': 'Reconstruction Log-Likelihood',
    'flexibilitydistance': 'Flexibility Distance',
    'maximummeandiscrepancy(mmd)': 'Maximum Mean Discrepancy (MMD)',
    'maximummeandiscrepancy': 'Maximum Mean Discrepancy (MMD)',
    'set-mmd(permutationinvariant)': 'Maximum Mean Discrepancy (MMD)',
    'setmmd(permutationinvariant)': 'Maximum Mean Discrepancy (MMD)',
    'set-mmd': 'Maximum Mean Discrepancy (MMD)',
    'acfdistributionmatch(ks)': 'ACF Distribution Match (KS)',
    'classicalstatistics': 'Classical Statistics',
    'tstr(trainonsynthetic,testonreal)': 'TSTR (Train on Synthetic, Test on Real)',
    'tstr': 'TSTR (Train on Synthetic, Test on Real)',
    'aggregatedprofiles(flexibilitydistance)': 'Aggregated Profiles (Flexibility Distance)',
    'aggregatedprofiles': 'Aggregated Profiles (Flexibility Distance)',
    'per-conditionevaluation': 'Per-Condition Evaluation',
    'perconditionevaluation': 'Per-Condition Evaluation',
    'perconditioneval': 'Per-Condition Evaluation',
    'visualevaluations': 'Visual Evaluations',
}


def _norm_metric_key(name: str) -> str:
    return ''.join(ch for ch in str(name).lower() if ch.isalnum() or ch in {'(', ')', '-', ','})


def _canonical_metric_name(name: str) -> str:
    key = _norm_metric_key(name)
    return _CANONICAL_METRIC_BY_KEY.get(key, str(name))


def _metric_goal(metric_name: str) -> str:
    if metric_name == 'TSTR (Train on Synthetic, Test on Real)':
        return 'target=1'
    if 'Log-Likelihood' in metric_name or metric_name == 'Visual Evaluations':
        return 'higher'
    return 'lower'


def _is_better(metric_name: str, model_value, baseline_value):
    try:
        m = float(model_value)
        b = float(baseline_value)
    except Exception:
        return None
    if not np.isfinite(m) or not np.isfinite(b):
        return None
    goal = _metric_goal(metric_name)
    if goal == 'higher':
        return m > b
    if goal == 'target=1':
        return abs(m - 1.0) < abs(b - 1.0)
    return m < b


def _fmt_val(v) -> str:
    if v is None:
        return '-'
    if isinstance(v, str):
        return v
    if isinstance(v, (int, float, np.floating)):
        return f'{float(v):.4f}'
    return str(v)


def _render_table(rows, headers):
    if _tabulate is not None:
        return _tabulate(rows, headers=headers, tablefmt='grid')
    matrix = [headers] + [[str(c) for c in r] for r in rows]
    widths = [max(len(row[i]) for row in matrix) for i in range(len(headers))]
    sep = '+' + '+'.join('-' * (w + 2) for w in widths) + '+'
    out = [sep]
    out.append('| ' + ' | '.join(headers[i].ljust(widths[i]) for i in range(len(headers))) + ' |')
    out.append(sep)
    for row in rows:
        out.append('| ' + ' | '.join(str(row[i]).ljust(widths[i]) for i in range(len(headers))) + ' |')
    out.append(sep)
    return '\n'.join(out)


def _extract_metric_map(data: dict) -> dict:
    if not isinstance(data, dict):
        return {}

    if isinstance(data.get('standalone_metrics'), dict) and data['standalone_metrics']:
        metric_map = {}
        for metric, payload in data['standalone_metrics'].items():
            canonical = _canonical_metric_name(metric)
            if isinstance(payload, dict):
                metric_map[canonical] = payload.get('value', None)
            else:
                metric_map[canonical] = payload
        return metric_map

    metric_map = {}
    ignored = {'standalone_metrics', 'results', 'metadata', 'run_info'}
    for key, value in data.items():
        if key in ignored:
            continue
        canonical = _canonical_metric_name(key)
        if isinstance(value, (int, float, np.floating)):
            metric_map[canonical] = float(value)
        elif isinstance(value, str) and value.upper() == 'ERROR':
            metric_map[canonical] = 'ERROR'
        elif isinstance(value, dict) and 'value' in value:
            metric_map[canonical] = value.get('value')
    return metric_map


def _coerce_condition_scalar(value):
    if isinstance(value, (int, float, np.floating)) and np.isfinite(float(value)):
        return float(value)
    if isinstance(value, dict):
        if isinstance(value.get('fd', None), (int, float, np.floating)):
            return float(value['fd'])
        diffs = value.get('differences', None)
        if isinstance(diffs, dict) and isinstance(diffs.get('overall_mean_abs_diff', None), (int, float, np.floating)):
            return float(diffs['overall_mean_abs_diff'])
        if isinstance(value.get('value', None), (int, float, np.floating)):
            return float(value['value'])
    return None


def _extract_per_condition_metric_map(model_dir: Path) -> dict:
    p = model_dir / 'ranked_phase_1_eval' / 'eval_results_condition.json'
    if not p.exists():
        return {}
    try:
        with open(p, 'r') as f:
            data = json.load(f)
    except Exception:
        return {}

    ignored = {'aggregated_profile_plots', 'feeder_mapping_path', 'min_samples_per_feeder', 'window_size', 'max_lag', 'min_samples_per_group', 'predictor_type'}
    out = {}
    for metric_name, by_condition in data.items():
        if metric_name in ignored or not isinstance(by_condition, dict):
            continue
        for condition_name, by_bucket in by_condition.items():
            if not isinstance(by_bucket, dict):
                continue
            for bucket, payload in by_bucket.items():
                scalar = _coerce_condition_scalar(payload)
                if scalar is None:
                    continue
                out[f'Per-Condition/{metric_name}/{condition_name}={bucket}'] = float(scalar)
    return out


def _load_training_config_used(model_dir: Path) -> tuple[dict, str]:
    cfg_path = model_dir / 'training_config_used.yaml'
    if not cfg_path.exists():
        return {}, 'missing'
    try:
        with open(cfg_path, 'r') as f:
            cfg = yaml.safe_load(f) or {}
        return cfg if isinstance(cfg, dict) else {}, str(cfg_path.relative_to(PROJECT_ROOT))
    except Exception:
        return {}, str(cfg_path.relative_to(PROJECT_ROOT))


def _flatten_tags(tags):
    if isinstance(tags, list):
        return ', '.join(str(t) for t in tags)
    return str(tags) if tags is not None else '-'


def _print_model_hyperparameters(model_dir: Path):
    cfg, cfg_src = _load_training_config_used(model_dir)
    if not cfg:
        print('Hyperparameters: training_config_used.yaml not found or unreadable.')
        return

    model = cfg.get('model', {}) if isinstance(cfg.get('model', {}), dict) else {}
    training = cfg.get('training', {}) if isinstance(cfg.get('training', {}), dict) else {}
    data = cfg.get('data', {}) if isinstance(cfg.get('data', {}), dict) else {}
    dataloader = data.get('dataloader', {}) if isinstance(data.get('dataloader', {}), dict) else {}
    window = data.get('window', {}) if isinstance(data.get('window', {}), dict) else {}
    prior = model.get('prior', {}) if isinstance(model.get('prior', {}), dict) else {}
    encoder = model.get('encoder', {}) if isinstance(model.get('encoder', {}), dict) else {}
    decoder = model.get('decoder', {}) if isinstance(model.get('decoder', {}), dict) else {}
    lr_scheduler = training.get('lr_scheduler', {}) if isinstance(training.get('lr_scheduler', {}), dict) else {}
    conditioning = cfg.get('conditioning', {}) if isinstance(cfg.get('conditioning', {}), dict) else {}

    items = [
        ('config', cfg_src),
        ('model.type', model.get('type')),
        ('model.latent_dim', model.get('latent_dim')),
        ('model.encoder.type', encoder.get('type')),
        ('model.decoder.type', decoder.get('type')),
        ('model.prior.type', prior.get('type')),
        ('model.prior.dictionary_size', prior.get('dictionary_size')),
        ('training.optimizer', training.get('optimizer')),
        ('training.learning_rate', training.get('learning_rate')),
        ('training.weight_decay', training.get('weight_decay')),
        ('training.num_epochs', training.get('num_epochs')),
        ('training.beta', training.get('beta')),
        ('training.weighted_loss', training.get('weighted_loss')),
        ('training.batch_size', dataloader.get('batch_size')),
        ('training.window.input_len', window.get('input_len')),
        ('training.window.stride', window.get('stride')),
        ('training.lr_scheduler', lr_scheduler.get('scheduler_type') if lr_scheduler.get('enabled') else 'disabled'),
        ('conditioning.tags', _flatten_tags(conditioning.get('tags'))),
    ]

    rows = [[k, str(v)] for k, v in items if v is not None]
    print('Hyperparameters used')
    print(_render_table(rows, headers=['Key', 'Value']))


def _candidate_baseline_dirs(prefix: str) -> list[Path]:
    out = []
    for d in sorted(HPC_RUNS_DIR.glob(f'{prefix}_*')):
        if d.is_dir():
            out.append(d)
    return out


def _pick_baseline_dir(prefix: str) -> Path | None:
    cands = _candidate_baseline_dirs(prefix)
    return cands[-1] if cands else None


MEAN_BASELINE_DIR = _pick_baseline_dir('AverageBaselineModel')
QUANTILE_BASELINE_DIR = _pick_baseline_dir('QuantileBaselineModel')


def _ranked_eval_json(model_dir: Path) -> Path:
    return model_dir / 'ranked_phase_1_eval' / 'eval_results.json'


def _ranked_condition_json(model_dir: Path) -> Path:
    return model_dir / 'ranked_phase_1_eval' / 'eval_results_condition.json'


def _aggregated_eval_json(model_dir: Path) -> Path:
    return model_dir / "aggregated_phase_eval" / "eval_results.json"


def _discover_model_dirs() -> list[Path]:
    model_dirs = []
    for d in sorted(HPC_RUNS_DIR.iterdir()):
        if not d.is_dir() or d.name == "UserProfiles":
            continue

        if _ranked_eval_json(d).exists() or _aggregated_eval_json(d).exists():
            model_dirs.append(d)

    return model_dirs

# 1-phase
MODEL_DIRS = _discover_model_dirs()
MODEL_RUNS = [d.name for d in MODEL_DIRS]

# 3-phase
MODEL_DIRS_PHASED = _discover_model_dirs_in(HPC_RUNS_DIR_PHASED)
MODEL_RUNS_PHASED = [d.name for d in MODEL_DIRS_PHASED]


print(f"Discovered 1-phase model runs ({len(MODEL_RUNS)}): {MODEL_RUNS}")
print(f"Discovered 3-phase model runs ({len(MODEL_RUNS_PHASED)}): {MODEL_RUNS_PHASED}")

def _pretty_name(run_name: str) -> str:
    if run_name.startswith('AutoRegressiveTransformerVAE_'):
        return 'ART-VAE'
    if run_name.startswith('DiffusionModel_'):
        return 'Diffusion'
    if run_name.startswith('CVAE_') and 'guide_cnn' in run_name:
        return 'CVAE-Guide-CNN'
    if run_name.startswith('CVAE_') and 'guide' in run_name:
        return 'CVAE-Guide'
    if run_name.startswith('CVAE_') and 'vamp' in run_name:
        return 'CVAE-Vamp'
    if run_name.startswith('CVAE_') and 'hierarcchy' in run_name:
        return 'CVAE-Hierarchy'
    if run_name.startswith('CVAE_'):
        return 'CVAE'
    if run_name.startswith('AverageBaselineModel_'):
        return 'Mean Baseline'
    if run_name.startswith('QuantileBaselineModel_'):
        return 'Quantile Baseline'
    return run_name


def _load_model_metrics_from_ranked_eval(model_dir: Path) -> dict:
    eval_path = _ranked_eval_json(model_dir)
    if not eval_path.exists():
        return {}
    with open(eval_path, 'r') as f:
        data = json.load(f)
    overall = _extract_metric_map(data)
    per_cond = _extract_per_condition_metric_map(model_dir)
    return {**overall, **per_cond}


def _bool_str(v):
    if v is None:
        return '-'
    return 'True' if bool(v) else 'False'


def _print_model_summary_with_two_baselines(model_name: str):
    model_dir = HPC_RUNS_DIR / model_name
    if not model_dir.exists():
        print(f'Model directory missing: {model_dir}')
        return None

    mean_metrics = _load_model_metrics_from_ranked_eval(MEAN_BASELINE_DIR) if MEAN_BASELINE_DIR is not None else {}
    quant_metrics = _load_model_metrics_from_ranked_eval(QUANTILE_BASELINE_DIR) if QUANTILE_BASELINE_DIR is not None else {}
    model_metrics = _load_model_metrics_from_ranked_eval(model_dir)

    print(f"\n=== {model_name} ===")
    _print_model_hyperparameters(model_dir)

    if not model_metrics:
        print(f'No metrics found in {_ranked_eval_json(model_dir)}')
        return None

    metric_names = sorted(model_metrics.keys())
    rows = []
    for metric in metric_names:
        mv = model_metrics.get(metric)
        bv_mean = mean_metrics.get(metric)
        bv_quant = quant_metrics.get(metric)

        better_mean = None if bv_mean is None else _is_better(metric, mv, bv_mean)
        better_quant = None if bv_quant is None else _is_better(metric, mv, bv_quant)

        rows.append([
            metric,
            _metric_goal(metric),
            _fmt_val(mv),
            _fmt_val(bv_mean),
            _fmt_val(bv_quant),
            _bool_str(better_mean),
            _bool_str(better_quant),
        ])

    print('\nEvaluation summary (model vs both baselines)')
    headers = [
        'Metric',
        'Goal',
        'Model',
        'Mean Baseline',
        'Quantile Baseline',
        'Better Than Mean',
        'Better Than Quantile',
    ]
    print(_render_table(rows, headers))
    return model_metrics


print('Helper setup complete.')
print(f'Project root: {PROJECT_ROOT}')
print(f'HPC runs folder: {HPC_RUNS_DIR}')
print(f'Discovered model runs ({len(MODEL_RUNS)}): {MODEL_RUNS}')
print(f'Mean baseline dir: {MEAN_BASELINE_DIR.name if MEAN_BASELINE_DIR else "MISSING"}')
print(f'Quantile baseline dir: {QUANTILE_BASELINE_DIR.name if QUANTILE_BASELINE_DIR else "MISSING"}')

Discovered 1-phase model runs (9): ['AutoRegressiveTransformerVAE_20260424_170101', 'AverageBaselineModel_20260425_192621', 'CVAE_20260424_163736', 'CVAE_20260424_164906_guide', 'CVAE_20260424_173354_guide_cnn', 'CVAE_20260424_174908_hierarcchy', 'CVAE_20260424_180137_vamp', 'DiffusionModel_20260424_171827', 'QuantileBaselineModel_20260425_193656']
Discovered 3-phase model runs (5): ['AutoRegressiveTransformerVAE_20260426_184212', 'AverageBaselineModel_20260426_185808', 'DiffusionModel_20260426_182935', 'QuantileBaselineModel_20260426_190605', 'SetGuideVAE_20260426_180021']
Helper setup complete.
Project root: /Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data
HPC runs folder: /Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/models/hpc_runs
Discovered model runs (9): ['AutoRegressiveTransformerVAE_20260424_170101', 'AverageBaselineModel_20260425_192621', 'CVAE_20260424_163736', 'CVAE_20260424_164906_guide', 'CVAE_20260424_173354_guide_cnn', 'CVAE_20260424_174908_hierarcchy', 'CVAE_20260424_180137_vamp', 'DiffusionModel_20260424_171827', 'QuantileBaselineModel_20260425_193656']
Mean baseline dir: AverageBaselineModel_20260425_192621
Quantile baseline dir: QuantileBaselineModel_20260425_193656

In [109]:
# Validate discovered runs and required ranked_phase_1 files.
print('Discovered non-baseline model runs:')
for i, run_name in enumerate(MODEL_RUNS, start=1):
    print(f'  {i}. {run_name}')

print('\nBaseline model folders:')
print('  Mean baseline:', MEAN_BASELINE_DIR if MEAN_BASELINE_DIR else 'MISSING')
print('  Quantile baseline:', QUANTILE_BASELINE_DIR if QUANTILE_BASELINE_DIR else 'MISSING')

for bname, bdir in [('Mean', MEAN_BASELINE_DIR), ('Quantile', QUANTILE_BASELINE_DIR)]:
    if bdir is None:
        continue
    eval_path = _ranked_eval_json(bdir)
    cond_path = _ranked_condition_json(bdir)
    print(f'  {bname} eval_results.json exists: {eval_path.exists()} ({eval_path})')
    print(f'  {bname} eval_results_condition.json exists: {cond_path.exists()} ({cond_path})')

Discovered non-baseline model runs:
  1. AutoRegressiveTransformerVAE_20260424_170101
  2. AverageBaselineModel_20260425_192621
  3. CVAE_20260424_163736
  4. CVAE_20260424_164906_guide
  5. CVAE_20260424_173354_guide_cnn
  6. CVAE_20260424_174908_hierarcchy
  7. CVAE_20260424_180137_vamp
  8. DiffusionModel_20260424_171827
  9. QuantileBaselineModel_20260425_193656

Baseline model folders:
  Mean baseline: /Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/models/hpc_runs/AverageBaselineModel_20260425_192621
  Quantile baseline: /Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/models/hpc_runs/QuantileBaselineModel_20260425_193656
  Mean eval_results.json exists: True (/Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/models/hpc_runs/AverageBaselineModel_20260425_192621/ranked_phase_1_eval/eval_results.json)
  Mean eval_results_condition.json exists: True (/Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/models/hpc_runs/AverageBaselineModel_20260425_192621/ranked_phase_1_eval/eval_results_condition.json)
  Quantile eval_results.json exists: True (/Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/models/hpc_runs/QuantileBaselineModel_20260425_193656/ranked_phase_1_eval/eval_results.json)
  Quantile eval_results_condition.json exists: True (/Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/models/hpc_runs/QuantileBaselineModel_20260425_193656/ranked_phase_1_eval/eval_results_condition.json)

In [110]:
# Quick preview of first discovered model's ranked_phase_1 eval file.
if not MODEL_RUNS:
    raise RuntimeError('No model runs with ranked_phase_1_eval/eval_results.json were discovered.')

_first_model_dir = HPC_RUNS_DIR / MODEL_RUNS[0]
_first_eval = _ranked_eval_json(_first_model_dir)
with open(_first_eval, 'r') as f:
    _first_payload = json.load(f)

print(f'Preview model: {MODEL_RUNS[0]}')
print(f'eval file: {_first_eval}')
print(f'top-level keys: {list(_first_payload.keys())[:20]}')

Preview model: AutoRegressiveTransformerVAE_20260424_170101
eval file: /Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/models/hpc_runs/AutoRegressiveTransformerVAE_20260424_170101/ranked_phase_1_eval/eval_results.json
top-level keys: ['Reconstruction RMSE', 'Reconstruction Log-Likelihood', 'Flexibility Distance', 'ACF Distribution Match (KS)', 'Classical Statistics', 'TSTR (Train on Synthetic, Test on Real)', 'Aggregated Profiles (Flexibility Distance)', 'Per-Condition Evaluation', 'Set-MMD (Permutation Invariant)']

In [111]:
# Baseline metrics loaded from baseline model folders.
mean_baseline_metrics = _load_model_metrics_from_ranked_eval(MEAN_BASELINE_DIR) if MEAN_BASELINE_DIR else {}
quantile_baseline_metrics = _load_model_metrics_from_ranked_eval(QUANTILE_BASELINE_DIR) if QUANTILE_BASELINE_DIR else {}

print('Mean baseline metrics loaded:', len(mean_baseline_metrics))
print('Quantile baseline metrics loaded:', len(quantile_baseline_metrics))

if not mean_baseline_metrics:
    print('Warning: mean baseline ranked_phase_1_eval/eval_results(.condition).json not found or empty.')
if not quantile_baseline_metrics:
    print('Warning: quantile baseline ranked_phase_1_eval/eval_results(.condition).json not found or empty.')

Mean baseline metrics loaded: 48
Quantile baseline metrics loaded: 48

### Per-Model Evaluation Cells

Run the cells below one by one. Each cell tries to run eval+visualization via `load_checkpoint` and falls back to existing artifacts if the model type is unsupported there.

#### 1-phase models

In [33]:
# 1) AutoRegressiveTransformerVAE
result_model_1 = _print_model_summary_with_two_baselines(MODEL_RUNS[0])

=== AutoRegressiveTransformerVAE_20260424_170101 ===
Hyperparameters used
+-----------------------------+----------------------------------------------------------------------------------------+
| Key                         | Value                                                                                  |
+-----------------------------+----------------------------------------------------------------------------------------+
| config                      | models/hpc_runs/AutoRegressiveTransformerVAE_20260424_170101/training_config_used.yaml |
| model.type                  | art                                                                                    |
| model.latent_dim            | 64                                                                                     |
| model.encoder.type          | dictionary                                                                             |
| model.decoder.type          | dictionary                                                                             |
| model.prior.type            | learnable_dictionary                                                                   |
| model.prior.dictionary_size | 256                                                                                    |
| training.optimizer          | adam                                                                                   |
| training.learning_rate      | 0.001                                                                                  |
| training.weight_decay       | 0.0001                                                                                 |
| training.num_epochs         | 40                                                                                     |
| training.beta               | 1.0                                                                                    |
| training.weighted_loss      | 0.2                                                                                    |
| training.window.input_len   | 24                                                                                     |
| training.window.stride      | 24                                                                                     |
| training.lr_scheduler       | cosine                                                                                 |
| conditioning.tags           | day_of_week, month_of_year, user_profile, holiday, heatpump_phase, ev_phase            |
+-----------------------------+----------------------------------------------------------------------------------------+

Evaluation summary (model vs both baselines)
+----------------------------------------------------------+----------+---------+---------------+-------------------+------------------+----------------------+
| Metric                                                   | Goal     | Model   | Mean Baseline | Quantile Baseline | Better Than Mean | Better Than Quantile |
+----------------------------------------------------------+----------+---------+---------------+-------------------+------------------+----------------------+
| ACF Distribution Match (KS)                              | lower    | 0.0833  | 0.8030        | 0.4747            | True             | True                 |
| Aggregated Profiles (Flexibility Distance)               | lower    | 28.7740 | 71.0541       | 66.4442           | True             | True                 |
| Classical Statistics                                     | lower    | 0.1468  | 0.2936        | 0.0915            | True             | False                |
| Flexibility Distance                                     | lower    | 0.6749  | 0.6086        | 0.5970            | False            | False                |
| Maximum Mean Discrepancy (MMD)                           | lower    | 0.0185  | 0.2857        | 0.1411            | True             | True                 |
| Per-Condition Evaluation                                 | lower    | 0.1011  | 0.5036        | 0.1838            | True             | True                 |
| Per-Condition/acf/day_of_week=1                          | lower    | 0.0803  | 0.8012        | 0.4727            | True             | True                 |
| Per-Condition/acf/month_of_year=1                        | lower    | 0.0803  | 0.8012        | 0.4727            | True             | True                 |
| Per-Condition/aggregated_profiles/day_of_week=1          | lower    | 28.7740 | 71.0541       | 66.4442           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.123212 | lower    | 16.4785 | 7.2421        | 6.2873            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.28232  | lower    | 19.4969 | 8.0837        | 6.3927            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.467100 | lower    | 16.7217 | 4.2582        | 4.7786            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.511350 | lower    | 7.0346  | 11.1840       | 13.4150           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.720906 | lower    | 44.8968 | 56.0907       | 53.0336           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.811037 | lower    | 10.5454 | 7.9064        | 7.1915            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.92816  | lower    | 27.0232 | 5.3347        | 12.2970           | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.930143 | lower    | 25.5428 | 7.9851        | 22.7173           | False            | False                |
| Per-Condition/aggregated_profiles/month_of_year=1        | lower    | 28.7740 | 71.0541       | 66.4442           | True             | True                 |
| Per-Condition/classical_statistics/day_of_week=1         | lower    | 0.2118  | 0.2416        | 0.0336            | True             | False                |
| Per-Condition/classical_statistics/month_of_year=1       | lower    | 0.2118  | 0.2416        | 0.0336            | True             | False                |
| Per-Condition/mmd/day_of_week=1                          | lower    | 0.1011  | 0.5036        | 0.1838            | True             | True                 |
| Per-Condition/mmd/month_of_year=1                        | lower    | 0.1011  | 0.5036        | 0.1838            | True             | True                 |
| Per-Condition/tstr/day_of_week=1                         | lower    | 0.7946  | 1.1711        | 1.2128            | True             | True                 |
| Per-Condition/tstr/month_of_year=1                       | lower    | 0.5577  | 0.6114        | 0.6134            | True             | True                 |
| Reconstruction Log-Likelihood                            | higher   | -1.8265 | -1.6458       | -1.6933           | False            | False                |
| Reconstruction RMSE                                      | lower    | 1.5031  | 1.2537        | 1.3087            | False            | False                |
| TSTR (Train on Synthetic, Test on Real)                  | target=1 | 1.1883  | 1.5000        | 1.2261            | True             | True                 |
+----------------------------------------------------------+----------+---------+---------------+-------------------+------------------+----------------------+

In [21]:
# 2) CVAE Dictionary
result_model_2 = _print_model_summary_with_two_baselines(MODEL_RUNS[1])

=== CVAE_20260424_163736 ===
Hyperparameters used
+-----------------------------+-----------------------------------------------------------------------------+
| Key                         | Value                                                                       |
+-----------------------------+-----------------------------------------------------------------------------+
| config                      | models/hpc_runs/CVAE_20260424_163736/training_config_used.yaml              |
| model.type                  | cvae                                                                        |
| model.latent_dim            | 64                                                                          |
| model.encoder.type          | mlp                                                                         |
| model.decoder.type          | mlp                                                                         |
| model.prior.type            | standard_gaussian                                                           |
| model.prior.dictionary_size | 256                                                                         |
| training.optimizer          | adam                                                                        |
| training.learning_rate      | 0.001                                                                       |
| training.weight_decay       | 0.0001                                                                      |
| training.num_epochs         | 40                                                                          |
| training.beta               | 1.0                                                                         |
| training.weighted_loss      | 0.2                                                                         |
| training.window.input_len   | 24                                                                          |
| training.window.stride      | 24                                                                          |
| training.lr_scheduler       | cosine                                                                      |
| conditioning.tags           | day_of_week, month_of_year, user_profile, holiday, heatpump_phase, ev_phase |
+-----------------------------+-----------------------------------------------------------------------------+

Evaluation summary (model vs both baselines)
+----------------------------------------------------------+----------+---------+---------------+-------------------+------------------+----------------------+
| Metric                                                   | Goal     | Model   | Mean Baseline | Quantile Baseline | Better Than Mean | Better Than Quantile |
+----------------------------------------------------------+----------+---------+---------------+-------------------+------------------+----------------------+
| ACF Distribution Match (KS)                              | lower    | 0.1921  | 0.8030        | 0.4747            | True             | True                 |
| Aggregated Profiles (Flexibility Distance)               | lower    | 54.1626 | 71.0541       | 66.4442           | True             | True                 |
| Classical Statistics                                     | lower    | 0.1349  | 0.2936        | 0.0915            | True             | False                |
| Flexibility Distance                                     | lower    | 0.4814  | 0.6086        | 0.5970            | True             | True                 |
| Maximum Mean Discrepancy (MMD)                           | lower    | 0.1332  | 0.2857        | 0.1411            | True             | True                 |
| Per-Condition Evaluation                                 | lower    | 0.2526  | 0.5036        | 0.1838            | True             | False                |
| Per-Condition/acf/day_of_week=1                          | lower    | 0.1947  | 0.8012        | 0.4727            | True             | True                 |
| Per-Condition/acf/month_of_year=1                        | lower    | 0.1947  | 0.8012        | 0.4727            | True             | True                 |
| Per-Condition/aggregated_profiles/day_of_week=1          | lower    | 54.1626 | 71.0541       | 66.4442           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.102134 | lower    | 2.3590  | 4.3761        | 6.3443            | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.122159 | lower    | 17.8648 | 11.3614       | 21.8818           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.123212 | lower    | 10.1763 | 7.2421        | 6.2873            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.168685 | lower    | 11.5149 | 5.6098        | 32.6963           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.211049 | lower    | 5.8424  | 7.0553        | 8.8745            | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.28232  | lower    | 1.9933  | 8.0837        | 6.3927            | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.440460 | lower    | 18.4801 | 12.9187       | 22.0230           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.444057 | lower    | 9.4585  | 5.7017        | 3.2690            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.449793 | lower    | 17.1822 | 11.5892       | 9.6517            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.467100 | lower    | 2.5545  | 4.2582        | 4.7786            | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.511350 | lower    | 6.3264  | 11.1840       | 13.4150           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.522789 | lower    | 9.1185  | 4.2282        | 9.6855            | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.555915 | lower    | 20.6892 | 27.3139       | 15.5569           | True             | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.600198 | lower    | 12.3770 | 6.3563        | 14.6688           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.630287 | lower    | 6.0803  | 5.8367        | 7.2854            | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.638770 | lower    | 49.4859 | 52.6477       | 32.6413           | True             | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.720906 | lower    | 51.1287 | 56.0907       | 53.0336           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.740978 | lower    | 10.8685 | 6.8011        | 7.5996            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.748487 | lower    | 9.9166  | 5.9774        | 4.2043            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.75344  | lower    | 14.3352 | 7.2062        | 6.4194            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.801609 | lower    | 61.7911 | 71.3707       | 68.2711           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.811037 | lower    | 3.4020  | 7.9064        | 7.1915            | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.909402 | lower    | 11.2350 | 7.1226        | 8.6659            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.925526 | lower    | 8.9651  | 13.7308       | 11.8360           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.92816  | lower    | 9.7473  | 5.3347        | 12.2970           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.930143 | lower    | 17.3252 | 7.9851        | 22.7173           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.938750 | lower    | 64.1953 | 67.2996       | 47.0040           | True             | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.95627  | lower    | 4.8363  | 1.5930        | 6.9858            | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.976304 | lower    | 4.1920  | 5.6920        | 5.2541            | True             | True                 |
| Per-Condition/aggregated_profiles/month_of_year=1        | lower    | 54.1626 | 71.0541       | 66.4442           | True             | True                 |
| Per-Condition/classical_statistics/day_of_week=1         | lower    | 0.0809  | 0.2416        | 0.0336            | True             | False                |
| Per-Condition/classical_statistics/month_of_year=1       | lower    | 0.0809  | 0.2416        | 0.0336            | True             | False                |
| Per-Condition/mmd/day_of_week=1                          | lower    | 0.2526  | 0.5036        | 0.1838            | True             | False                |
| Per-Condition/mmd/month_of_year=1                        | lower    | 0.2526  | 0.5036        | 0.1838            | True             | False                |
| Per-Condition/tstr/day_of_week=1                         | lower    | 1.1570  | 1.1711        | 1.2128            | True             | True                 |
| Per-Condition/tstr/month_of_year=1                       | lower    | 0.6114  | 0.6114        | 0.6134            | False            | True                 |
| Reconstruction Log-Likelihood                            | higher   | -1.4018 | -1.6458       | -1.6933           | True             | True                 |
| Reconstruction RMSE                                      | lower    | 0.9830  | 1.2537        | 1.3087            | True             | True                 |
| TSTR (Train on Synthetic, Test on Real)                  | target=1 | 1.2189  | 1.5000        | 1.2261            | True             | True                 |
+----------------------------------------------------------+----------+---------+---------------+-------------------+------------------+----------------------+

In [22]:
# 3) CVAE Dictionary + Hierarchy
result_model_3 = _print_model_summary_with_two_baselines(MODEL_RUNS[2])

=== CVAE_20260424_164906_guide ===
Hyperparameters used
+-----------------------------+-----------------------------------------------------------------------------+
| Key                         | Value                                                                       |
+-----------------------------+-----------------------------------------------------------------------------+
| config                      | models/hpc_runs/CVAE_20260424_164906_guide/training_config_used.yaml        |
| model.type                  | cvae                                                                        |
| model.latent_dim            | 64                                                                          |
| model.encoder.type          | dictionary                                                                  |
| model.decoder.type          | dictionary                                                                  |
| model.prior.type            | learnable_dictionary                                                        |
| model.prior.dictionary_size | 256                                                                         |
| training.optimizer          | adam                                                                        |
| training.learning_rate      | 0.001                                                                       |
| training.weight_decay       | 0.0001                                                                      |
| training.num_epochs         | 40                                                                          |
| training.beta               | 1.0                                                                         |
| training.weighted_loss      | 0.2                                                                         |
| training.window.input_len   | 24                                                                          |
| training.window.stride      | 24                                                                          |
| training.lr_scheduler       | cosine                                                                      |
| conditioning.tags           | day_of_week, month_of_year, user_profile, holiday, heatpump_phase, ev_phase |
+-----------------------------+-----------------------------------------------------------------------------+

Evaluation summary (model vs both baselines)
+----------------------------------------------------------+----------+---------+---------------+-------------------+------------------+----------------------+
| Metric                                                   | Goal     | Model   | Mean Baseline | Quantile Baseline | Better Than Mean | Better Than Quantile |
+----------------------------------------------------------+----------+---------+---------------+-------------------+------------------+----------------------+
| ACF Distribution Match (KS)                              | lower    | 0.0723  | 0.8030        | 0.4747            | True             | True                 |
| Aggregated Profiles (Flexibility Distance)               | lower    | 56.6864 | 71.0541       | 66.4442           | True             | True                 |
| Classical Statistics                                     | lower    | 0.1689  | 0.2936        | 0.0915            | True             | False                |
| Flexibility Distance                                     | lower    | 0.5123  | 0.6086        | 0.5970            | True             | True                 |
| Maximum Mean Discrepancy (MMD)                           | lower    | 0.0772  | 0.2857        | 0.1411            | True             | True                 |
| Per-Condition Evaluation                                 | lower    | 0.0775  | 0.5036        | 0.1838            | True             | True                 |
| Per-Condition/acf/day_of_week=1                          | lower    | 0.0745  | 0.8012        | 0.4727            | True             | True                 |
| Per-Condition/acf/month_of_year=1                        | lower    | 0.0745  | 0.8012        | 0.4727            | True             | True                 |
| Per-Condition/aggregated_profiles/day_of_week=1          | lower    | 56.6864 | 71.0541       | 66.4442           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.102134 | lower    | 3.8771  | 4.3761        | 6.3443            | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.122159 | lower    | 19.0209 | 11.3614       | 21.8818           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.123212 | lower    | 9.2700  | 7.2421        | 6.2873            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.168685 | lower    | 3.4777  | 5.6098        | 32.6963           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.211049 | lower    | 8.7391  | 7.0553        | 8.8745            | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.28232  | lower    | 7.7654  | 8.0837        | 6.3927            | True             | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.440460 | lower    | 18.0191 | 12.9187       | 22.0230           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.444057 | lower    | 4.9442  | 5.7017        | 3.2690            | True             | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.449793 | lower    | 16.6927 | 11.5892       | 9.6517            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.467100 | lower    | 5.7943  | 4.2582        | 4.7786            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.511350 | lower    | 9.2768  | 11.1840       | 13.4150           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.522789 | lower    | 4.6227  | 4.2282        | 9.6855            | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.555915 | lower    | 24.4375 | 27.3139       | 15.5569           | True             | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.600198 | lower    | 6.9499  | 6.3563        | 14.6688           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.630287 | lower    | 8.8778  | 5.8367        | 7.2854            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.638770 | lower    | 49.4264 | 52.6477       | 32.6413           | True             | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.720906 | lower    | 52.6013 | 56.0907       | 53.0336           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.740978 | lower    | 9.4711  | 6.8011        | 7.5996            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.748487 | lower    | 7.4781  | 5.9774        | 4.2043            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.75344  | lower    | 13.4615 | 7.2062        | 6.4194            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.801609 | lower    | 59.1986 | 71.3707       | 68.2711           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.811037 | lower    | 5.0207  | 7.9064        | 7.1915            | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.909402 | lower    | 10.1340 | 7.1226        | 8.6659            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.925526 | lower    | 11.5819 | 13.7308       | 11.8360           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.92816  | lower    | 16.2940 | 5.3347        | 12.2970           | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.930143 | lower    | 12.5422 | 7.9851        | 22.7173           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.938750 | lower    | 60.5499 | 67.2996       | 47.0040           | True             | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.95627  | lower    | 5.9522  | 1.5930        | 6.9858            | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.976304 | lower    | 4.3073  | 5.6920        | 5.2541            | True             | True                 |
| Per-Condition/aggregated_profiles/month_of_year=1        | lower    | 56.6864 | 71.0541       | 66.4442           | True             | True                 |
| Per-Condition/classical_statistics/day_of_week=1         | lower    | 0.1169  | 0.2416        | 0.0336            | True             | False                |
| Per-Condition/classical_statistics/month_of_year=1       | lower    | 0.1169  | 0.2416        | 0.0336            | True             | False                |
| Per-Condition/mmd/day_of_week=1                          | lower    | 0.0775  | 0.5036        | 0.1838            | True             | True                 |
| Per-Condition/mmd/month_of_year=1                        | lower    | 0.0775  | 0.5036        | 0.1838            | True             | True                 |
| Per-Condition/tstr/day_of_week=1                         | lower    | 1.1364  | 1.1711        | 1.2128            | True             | True                 |
| Per-Condition/tstr/month_of_year=1                       | lower    | 0.6118  | 0.6114        | 0.6134            | False            | True                 |
| Reconstruction Log-Likelihood                            | higher   | -1.5879 | -1.6458       | -1.6933           | True             | True                 |
| Reconstruction RMSE                                      | lower    | 1.1840  | 1.2537        | 1.3087            | True             | True                 |
| TSTR (Train on Synthetic, Test on Real)                  | target=1 | 1.1953  | 1.5000        | 1.2261            | True             | True                 |
+----------------------------------------------------------+----------+---------+---------------+-------------------+------------------+----------------------+

In [23]:
# 4) CVAE Dictionary + Vamp Prior
result_model_4 = _print_model_summary_with_two_baselines(MODEL_RUNS[3])

=== CVAE_20260424_173354_guide_cnn ===
Hyperparameters used
+-----------------------------+-----------------------------------------------------------------------------+
| Key                         | Value                                                                       |
+-----------------------------+-----------------------------------------------------------------------------+
| config                      | models/hpc_runs/CVAE_20260424_173354_guide_cnn/training_config_used.yaml    |
| model.type                  | cvae                                                                        |
| model.latent_dim            | 64                                                                          |
| model.encoder.type          | dictionary_cnn                                                              |
| model.decoder.type          | dictionary_cnn                                                              |
| model.prior.type            | learnable_dictionary                                                        |
| model.prior.dictionary_size | 256                                                                         |
| training.optimizer          | adam                                                                        |
| training.learning_rate      | 0.001                                                                       |
| training.weight_decay       | 0.0001                                                                      |
| training.num_epochs         | 40                                                                          |
| training.beta               | 1.0                                                                         |
| training.weighted_loss      | 0.2                                                                         |
| training.window.input_len   | 24                                                                          |
| training.window.stride      | 24                                                                          |
| training.lr_scheduler       | cosine                                                                      |
| conditioning.tags           | day_of_week, month_of_year, user_profile, holiday, heatpump_phase, ev_phase |
+-----------------------------+-----------------------------------------------------------------------------+

Evaluation summary (model vs both baselines)
+----------------------------------------------------------+----------+---------+---------------+-------------------+------------------+----------------------+
| Metric                                                   | Goal     | Model   | Mean Baseline | Quantile Baseline | Better Than Mean | Better Than Quantile |
+----------------------------------------------------------+----------+---------+---------------+-------------------+------------------+----------------------+
| ACF Distribution Match (KS)                              | lower    | 0.0528  | 0.8030        | 0.4747            | True             | True                 |
| Aggregated Profiles (Flexibility Distance)               | lower    | 59.6773 | 71.0541       | 66.4442           | True             | True                 |
| Classical Statistics                                     | lower    | 0.1537  | 0.2936        | 0.0915            | True             | False                |
| Flexibility Distance                                     | lower    | 0.4137  | 0.6086        | 0.5970            | True             | True                 |
| Maximum Mean Discrepancy (MMD)                           | lower    | 0.0641  | 0.2857        | 0.1411            | True             | True                 |
| Per-Condition Evaluation                                 | lower    | 0.0743  | 0.5036        | 0.1838            | True             | True                 |
| Per-Condition/acf/day_of_week=1                          | lower    | 0.0560  | 0.8012        | 0.4727            | True             | True                 |
| Per-Condition/acf/month_of_year=1                        | lower    | 0.0560  | 0.8012        | 0.4727            | True             | True                 |
| Per-Condition/aggregated_profiles/day_of_week=1          | lower    | 59.6773 | 71.0541       | 66.4442           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.102134 | lower    | 8.3791  | 4.3761        | 6.3443            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.122159 | lower    | 8.0630  | 11.3614       | 21.8818           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.123212 | lower    | 15.1235 | 7.2421        | 6.2873            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.168685 | lower    | 18.3669 | 5.6098        | 32.6963           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.211049 | lower    | 8.3298  | 7.0553        | 8.8745            | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.28232  | lower    | 3.4913  | 8.0837        | 6.3927            | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.440460 | lower    | 18.0898 | 12.9187       | 22.0230           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.444057 | lower    | 11.2712 | 5.7017        | 3.2690            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.449793 | lower    | 13.6603 | 11.5892       | 9.6517            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.467100 | lower    | 2.7877  | 4.2582        | 4.7786            | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.511350 | lower    | 5.9522  | 11.1840       | 13.4150           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.522789 | lower    | 10.9591 | 4.2282        | 9.6855            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.555915 | lower    | 19.1870 | 27.3139       | 15.5569           | True             | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.600198 | lower    | 9.9815  | 6.3563        | 14.6688           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.630287 | lower    | 7.0068  | 5.8367        | 7.2854            | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.638770 | lower    | 46.8399 | 52.6477       | 32.6413           | True             | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.720906 | lower    | 55.2121 | 56.0907       | 53.0336           | True             | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.740978 | lower    | 7.5495  | 6.8011        | 7.5996            | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.748487 | lower    | 3.2654  | 5.9774        | 4.2043            | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.75344  | lower    | 13.2638 | 7.2062        | 6.4194            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.801609 | lower    | 65.9891 | 71.3707       | 68.2711           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.811037 | lower    | 3.0899  | 7.9064        | 7.1915            | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.909402 | lower    | 12.2945 | 7.1226        | 8.6659            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.925526 | lower    | 6.1277  | 13.7308       | 11.8360           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.92816  | lower    | 8.9327  | 5.3347        | 12.2970           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.930143 | lower    | 6.4212  | 7.9851        | 22.7173           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.938750 | lower    | 63.5447 | 67.2996       | 47.0040           | True             | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.95627  | lower    | 9.0545  | 1.5930        | 6.9858            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.976304 | lower    | 5.0780  | 5.6920        | 5.2541            | True             | True                 |
| Per-Condition/aggregated_profiles/month_of_year=1        | lower    | 59.6773 | 71.0541       | 66.4442           | True             | True                 |
| Per-Condition/classical_statistics/day_of_week=1         | lower    | 0.1016  | 0.2416        | 0.0336            | True             | False                |
| Per-Condition/classical_statistics/month_of_year=1       | lower    | 0.1016  | 0.2416        | 0.0336            | True             | False                |
| Per-Condition/mmd/day_of_week=1                          | lower    | 0.0743  | 0.5036        | 0.1838            | True             | True                 |
| Per-Condition/mmd/month_of_year=1                        | lower    | 0.0743  | 0.5036        | 0.1838            | True             | True                 |
| Per-Condition/tstr/day_of_week=1                         | lower    | 1.0564  | 1.1711        | 1.2128            | True             | True                 |
| Per-Condition/tstr/month_of_year=1                       | lower    | 0.6171  | 0.6114        | 0.6134            | False            | False                |
| Reconstruction Log-Likelihood                            | higher   | -1.4248 | -1.6458       | -1.6933           | True             | True                 |
| Reconstruction RMSE                                      | lower    | 1.0059  | 1.2537        | 1.3087            | True             | True                 |
| TSTR (Train on Synthetic, Test on Real)                  | target=1 | 1.2705  | 1.5000        | 1.2261            | True             | False                |
+----------------------------------------------------------+----------+---------+---------------+-------------------+------------------+----------------------+

In [24]:
# 5) CVAE Gaussian
result_model_5 = _print_model_summary_with_two_baselines(MODEL_RUNS[4])

=== CVAE_20260424_174908_hierarcchy ===
Hyperparameters used
+-----------------------------+-----------------------------------------------------------------------------+
| Key                         | Value                                                                       |
+-----------------------------+-----------------------------------------------------------------------------+
| config                      | models/hpc_runs/CVAE_20260424_174908_hierarcchy/training_config_used.yaml   |
| model.type                  | cvae                                                                        |
| model.latent_dim            | 64                                                                          |
| model.encoder.type          | dictionary                                                                  |
| model.decoder.type          | dictionary                                                                  |
| model.prior.type            | learnable_dictionary                                                        |
| model.prior.dictionary_size | 256                                                                         |
| training.optimizer          | adam                                                                        |
| training.learning_rate      | 0.001                                                                       |
| training.weight_decay       | 0.0001                                                                      |
| training.num_epochs         | 40                                                                          |
| training.beta               | 1.0                                                                         |
| training.weighted_loss      | 0.2                                                                         |
| training.window.input_len   | 24                                                                          |
| training.window.stride      | 24                                                                          |
| training.lr_scheduler       | cosine                                                                      |
| conditioning.tags           | day_of_week, month_of_year, user_profile, holiday, heatpump_phase, ev_phase |
+-----------------------------+-----------------------------------------------------------------------------+

Evaluation summary (model vs both baselines)
+----------------------------------------------------------+----------+---------+---------------+-------------------+------------------+----------------------+
| Metric                                                   | Goal     | Model   | Mean Baseline | Quantile Baseline | Better Than Mean | Better Than Quantile |
+----------------------------------------------------------+----------+---------+---------------+-------------------+------------------+----------------------+
| ACF Distribution Match (KS)                              | lower    | 0.0896  | 0.8030        | 0.4747            | True             | True                 |
| Aggregated Profiles (Flexibility Distance)               | lower    | 46.6229 | 71.0541       | 66.4442           | True             | True                 |
| Classical Statistics                                     | lower    | 0.1598  | 0.2936        | 0.0915            | True             | False                |
| Flexibility Distance                                     | lower    | 0.4321  | 0.6086        | 0.5970            | True             | True                 |
| Maximum Mean Discrepancy (MMD)                           | lower    | 0.0778  | 0.2857        | 0.1411            | True             | True                 |
| Per-Condition Evaluation                                 | lower    | 0.0922  | 0.5036        | 0.1838            | True             | True                 |
| Per-Condition/acf/day_of_week=1                          | lower    | 0.0864  | 0.8012        | 0.4727            | True             | True                 |
| Per-Condition/acf/month_of_year=1                        | lower    | 0.0864  | 0.8012        | 0.4727            | True             | True                 |
| Per-Condition/aggregated_profiles/day_of_week=1          | lower    | 46.6229 | 71.0541       | 66.4442           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.102134 | lower    | 5.6910  | 4.3761        | 6.3443            | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.122159 | lower    | 19.2517 | 11.3614       | 21.8818           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.123212 | lower    | 10.7766 | 7.2421        | 6.2873            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.168685 | lower    | 13.3512 | 5.6098        | 32.6963           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.211049 | lower    | 7.5149  | 7.0553        | 8.8745            | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.28232  | lower    | 2.0338  | 8.0837        | 6.3927            | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.440460 | lower    | 11.3727 | 12.9187       | 22.0230           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.444057 | lower    | 7.0100  | 5.7017        | 3.2690            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.449793 | lower    | 17.7881 | 11.5892       | 9.6517            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.467100 | lower    | 2.7613  | 4.2582        | 4.7786            | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.511350 | lower    | 7.0559  | 11.1840       | 13.4150           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.522789 | lower    | 5.3962  | 4.2282        | 9.6855            | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.555915 | lower    | 21.8997 | 27.3139       | 15.5569           | True             | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.600198 | lower    | 9.1346  | 6.3563        | 14.6688           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.630287 | lower    | 6.7693  | 5.8367        | 7.2854            | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.638770 | lower    | 44.9994 | 52.6477       | 32.6413           | True             | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.720906 | lower    | 49.9876 | 56.0907       | 53.0336           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.740978 | lower    | 10.0164 | 6.8011        | 7.5996            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.748487 | lower    | 8.5538  | 5.9774        | 4.2043            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.75344  | lower    | 7.6912  | 7.2062        | 6.4194            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.801609 | lower    | 63.2434 | 71.3707       | 68.2711           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.811037 | lower    | 4.0135  | 7.9064        | 7.1915            | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.909402 | lower    | 13.8724 | 7.1226        | 8.6659            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.925526 | lower    | 9.4681  | 13.7308       | 11.8360           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.92816  | lower    | 15.1781 | 5.3347        | 12.2970           | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.930143 | lower    | 9.3341  | 7.9851        | 22.7173           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.938750 | lower    | 69.0271 | 67.2996       | 47.0040           | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.95627  | lower    | 3.3300  | 1.5930        | 6.9858            | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.976304 | lower    | 4.6064  | 5.6920        | 5.2541            | True             | True                 |
| Per-Condition/aggregated_profiles/month_of_year=1        | lower    | 46.6229 | 71.0541       | 66.4442           | True             | True                 |
| Per-Condition/classical_statistics/day_of_week=1         | lower    | 0.1078  | 0.2416        | 0.0336            | True             | False                |
| Per-Condition/classical_statistics/month_of_year=1       | lower    | 0.1078  | 0.2416        | 0.0336            | True             | False                |
| Per-Condition/mmd/day_of_week=1                          | lower    | 0.0922  | 0.5036        | 0.1838            | True             | True                 |
| Per-Condition/mmd/month_of_year=1                        | lower    | 0.0922  | 0.5036        | 0.1838            | True             | True                 |
| Per-Condition/tstr/day_of_week=1                         | lower    | 1.1625  | 1.1711        | 1.2128            | True             | True                 |
| Per-Condition/tstr/month_of_year=1                       | lower    | 0.6103  | 0.6114        | 0.6134            | True             | True                 |
| Reconstruction Log-Likelihood                            | higher   | -1.4545 | -1.6458       | -1.6933           | True             | True                 |
| Reconstruction RMSE                                      | lower    | 1.0362  | 1.2537        | 1.3087            | True             | True                 |
| TSTR (Train on Synthetic, Test on Real)                  | target=1 | 1.1750  | 1.5000        | 1.2261            | True             | True                 |
+----------------------------------------------------------+----------+---------+---------------+-------------------+------------------+----------------------+

In [25]:
# 6) Diffusion
result_model_6 = _print_model_summary_with_two_baselines(MODEL_RUNS[5])

=== CVAE_20260424_180137_vamp ===
Hyperparameters used
+-----------------------------+-----------------------------------------------------------------------------+
| Key                         | Value                                                                       |
+-----------------------------+-----------------------------------------------------------------------------+
| config                      | models/hpc_runs/CVAE_20260424_180137_vamp/training_config_used.yaml         |
| model.type                  | cvae                                                                        |
| model.latent_dim            | 64                                                                          |
| model.encoder.type          | dictionary                                                                  |
| model.decoder.type          | dictionary                                                                  |
| model.prior.type            | vampprior                                                                   |
| model.prior.dictionary_size | 256                                                                         |
| training.optimizer          | adam                                                                        |
| training.learning_rate      | 0.001                                                                       |
| training.weight_decay       | 0.0001                                                                      |
| training.num_epochs         | 40                                                                          |
| training.beta               | 1.0                                                                         |
| training.weighted_loss      | 0.2                                                                         |
| training.window.input_len   | 24                                                                          |
| training.window.stride      | 24                                                                          |
| training.lr_scheduler       | cosine                                                                      |
| conditioning.tags           | day_of_week, month_of_year, user_profile, holiday, heatpump_phase, ev_phase |
+-----------------------------+-----------------------------------------------------------------------------+

Evaluation summary (model vs both baselines)
+----------------------------------------------------------+----------+---------+---------------+-------------------+------------------+----------------------+
| Metric                                                   | Goal     | Model   | Mean Baseline | Quantile Baseline | Better Than Mean | Better Than Quantile |
+----------------------------------------------------------+----------+---------+---------------+-------------------+------------------+----------------------+
| ACF Distribution Match (KS)                              | lower    | 0.0715  | 0.8030        | 0.4747            | True             | True                 |
| Aggregated Profiles (Flexibility Distance)               | lower    | 54.2097 | 71.0541       | 66.4442           | True             | True                 |
| Classical Statistics                                     | lower    | 0.1736  | 0.2936        | 0.0915            | True             | False                |
| Flexibility Distance                                     | lower    | 0.4415  | 0.6086        | 0.5970            | True             | True                 |
| Maximum Mean Discrepancy (MMD)                           | lower    | 0.0816  | 0.2857        | 0.1411            | True             | True                 |
| Per-Condition Evaluation                                 | lower    | 0.0860  | 0.5036        | 0.1838            | True             | True                 |
| Per-Condition/acf/day_of_week=1                          | lower    | 0.0730  | 0.8012        | 0.4727            | True             | True                 |
| Per-Condition/acf/month_of_year=1                        | lower    | 0.0730  | 0.8012        | 0.4727            | True             | True                 |
| Per-Condition/aggregated_profiles/day_of_week=1          | lower    | 54.2097 | 71.0541       | 66.4442           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.102134 | lower    | 3.4207  | 4.3761        | 6.3443            | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.122159 | lower    | 18.9854 | 11.3614       | 21.8818           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.123212 | lower    | 13.4306 | 7.2421        | 6.2873            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.168685 | lower    | 8.1640  | 5.6098        | 32.6963           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.211049 | lower    | 7.8716  | 7.0553        | 8.8745            | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.28232  | lower    | 5.1863  | 8.0837        | 6.3927            | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.440460 | lower    | 17.8741 | 12.9187       | 22.0230           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.444057 | lower    | 5.0094  | 5.7017        | 3.2690            | True             | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.449793 | lower    | 26.5787 | 11.5892       | 9.6517            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.467100 | lower    | 4.5058  | 4.2582        | 4.7786            | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.511350 | lower    | 7.9519  | 11.1840       | 13.4150           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.522789 | lower    | 3.4228  | 4.2282        | 9.6855            | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.555915 | lower    | 24.5130 | 27.3139       | 15.5569           | True             | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.600198 | lower    | 6.4535  | 6.3563        | 14.6688           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.630287 | lower    | 6.1095  | 5.8367        | 7.2854            | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.638770 | lower    | 49.0263 | 52.6477       | 32.6413           | True             | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.720906 | lower    | 52.0768 | 56.0907       | 53.0336           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.740978 | lower    | 8.0623  | 6.8011        | 7.5996            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.748487 | lower    | 11.4065 | 5.9774        | 4.2043            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.75344  | lower    | 19.0115 | 7.2062        | 6.4194            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.801609 | lower    | 67.4739 | 71.3707       | 68.2711           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.811037 | lower    | 4.1789  | 7.9064        | 7.1915            | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.909402 | lower    | 10.4173 | 7.1226        | 8.6659            | False            | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.925526 | lower    | 11.3355 | 13.7308       | 11.8360           | True             | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.92816  | lower    | 9.5544  | 5.3347        | 12.2970           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.930143 | lower    | 9.5316  | 7.9851        | 22.7173           | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.938750 | lower    | 64.3588 | 67.2996       | 47.0040           | True             | False                |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.95627  | lower    | 2.0244  | 1.5930        | 6.9858            | False            | True                 |
| Per-Condition/aggregated_profiles/feeder=LvFeeder.976304 | lower    | 5.7788  | 5.6920        | 5.2541            | False            | False                |
| Per-Condition/aggregated_profiles/month_of_year=1        | lower    | 54.2097 | 71.0541       | 66.4442           | True             | True                 |
| Per-Condition/classical_statistics/day_of_week=1         | lower    | 0.1216  | 0.2416        | 0.0336            | True             | False                |
| Per-Condition/classical_statistics/month_of_year=1       | lower    | 0.1216  | 0.2416        | 0.0336            | True             | False                |
| Per-Condition/mmd/day_of_week=1                          | lower    | 0.0860  | 0.5036        | 0.1838            | True             | True                 |
| Per-Condition/mmd/month_of_year=1                        | lower    | 0.0860  | 0.5036        | 0.1838            | True             | True                 |
| Per-Condition/tstr/day_of_week=1                         | lower    | 1.1420  | 1.1711        | 1.2128            | True             | True                 |
| Per-Condition/tstr/month_of_year=1                       | lower    | 0.6143  | 0.6114        | 0.6134            | False            | False                |
| Reconstruction Log-Likelihood                            | higher   | -1.4375 | -1.6458       | -1.6933           | True             | True                 |
| Reconstruction RMSE                                      | lower    | 1.0182  | 1.2537        | 1.3087            | True             | True                 |
| TSTR (Train on Synthetic, Test on Real)                  | target=1 | 1.2018  | 1.5000        | 1.2261            | True             | True                 |
+----------------------------------------------------------+----------+---------+---------------+-------------------+------------------+----------------------+

#### 3-phase models

In [ ]:
# 1) AutoRegressiveTransformerVAE
result_model_1 = _print_model_summary_with_two_baselines(MODEL_RUNS[0])

In [26]:
# 7) SetGuideVAE (3-phase) - use aggregated phase eval artifacts
setguide_model_dir = HPC_RUNS_DIR / 'SetGuideVAE_DictionaryCoder_20260416_103152'
setguide_config = setguide_model_dir / 'training_config_used.yaml'
shared_eval_plan_setguide = _build_shared_eval_plan(
    data_variant='3phase_15min',
    max_files=None,
    seed=42,
    config_path=setguide_config if setguide_config.exists() else CONFIG_PATH,
    )

print('\n=== SetGuideVAE_DictionaryCoder_20260416_103152 ===')
_print_model_hyperparameters(setguide_model_dir)

setguide_agg_eval_json = setguide_model_dir / 'aggregated_phase_eval' / 'eval_results.json'
if setguide_agg_eval_json.exists():
    print('Using aggregated SetGuide evaluation results.')
    result_setguide = _display_eval_results(setguide_agg_eval_json, shared_plan=shared_eval_plan_setguide)
    _show_visual_artifacts(setguide_agg_eval_json.parent)
else:
    print('Aggregated eval not found, falling back to top-level SetGuide eval_results.json.')
    result_setguide = evaluate_model_run(
        model_name='SetGuideVAE_DictionaryCoder_20260416_103152',
        shared_plan=shared_eval_plan_setguide,
        rerun_if_supported=False,
        )

NameError: name '_build_shared_eval_plan' is not defined

### Overall Comparison Across All HPC Runs

This cell collects each model folder's `eval_results.json` and compares them side-by-side using `compare_eval`.

#### 1-phase

In [113]:
import importlib
import pandas as pd
import evaluation.compare_models as compare_models

importlib.reload(compare_models)

ModelComparator = compare_models.PhasedModelComparator

comparison_output_dir = PROJECT_ROOT / "evaluation_comparison_hpc_runs"
comparator = ModelComparator(output_dir=str(comparison_output_dir))

DISPLAY_MODEL_NAMES = {
    "AutoRegressiveTransformerVAE_20260424_170101": "ART-VAE",
    "CVAE_20260424_163736": "CVAE",
    "CVAE_20260424_164906_guide": "GUIDE-VAE",
    "CVAE_20260424_173354_guide_cnn": "GUIDE-VAE-CNN",
    "CVAE_20260424_174908_hierarcchy": "GUIDE-VAE-Hierarchy",
    "CVAE_20260424_180137_vamp": "GUIDE-VAE-Vamp",
    "DiffusionModel_20260424_171827": "Diffusion",
    "AverageBaselineModel_20260425_192621": "Avg Baseline",
    "QuantileBaselineModel_20260425_193656": "Quantile Baseline",
}

added = []

for model_name in MODEL_RUNS:
    model_dir = HPC_RUNS_DIR / model_name
    eval_json = model_dir / "aggregated_phase_eval" / "eval_results.json"

    if eval_json.exists():
        display_name = DISPLAY_MODEL_NAMES.get(model_name, model_name)

        # IMPORTANT: pass model_dir, not eval_json
        comparator.add_model(display_name, str(model_dir))

        added.append(display_name)
    else:
        print(f"Skipping {model_name}: eval results not found at {eval_json}")

if not added:
    print("No eval result files found. Run model cells first.")
else:
    print(f"Comparing {len(added)} models...")
    print("Legend names:", ", ".join(added))

    # Compute averages before making notebook table
    comparator._compute_averages("aggregated_phase")

    # Build readable notebook table
    all_metrics = sorted({
        metric
        for model_name in added
        for metric, value in comparator.models_data[model_name]["aggregated_phase"].items()
        if isinstance(value, (int, float))
    })

    # Put summary scores last
    preferred_last = [
        "Avg MinMax Synthetic Score",
        "Avg MinMax Reconstruction Score",
        "BEST overall synthetic score",
        "BEST overall reconstruction score",
    ]

    non_summary = [m for m in all_metrics if m not in preferred_last]
    summary = [m for m in preferred_last if m in all_metrics]
    all_metrics = non_summary + summary

    table_df = pd.DataFrame(index=all_metrics, columns=added, dtype=float)

    for model_name in added:
        metrics = comparator.models_data[model_name]["aggregated_phase"]
        for metric_name in all_metrics:
            metric_val = metrics.get(metric_name)
            if isinstance(metric_val, (int, float)):
                table_df.loc[metric_name, model_name] = metric_val

    table_df.index.name = "Metric"

    print("\nReadable model comparison table:")
    display(table_df.round(4))

    comparator.compare()

    print(f"Comparison artifacts written to: {comparison_output_dir}")

Comparing 9 models...
Legend names: ART-VAE, Avg Baseline, CVAE, GUIDE-VAE, GUIDE-VAE-CNN, GUIDE-VAE-Hierarchy, GUIDE-VAE-Vamp, Diffusion, Quantile Baseline

Readable model comparison table:

,ART-VAE,Avg Baseline,CVAE,GUIDE-VAE,GUIDE-VAE-CNN,GUIDE-VAE-Hierarchy,GUIDE-VAE-Vamp,Diffusion,Quantile Baseline
Metric,,,,,,,,,
ACF Distribution Match (KS),0.0833,0.8030,0.1921,0.0723,0.0528,0.0896,0.0715,0.0470,0.4747
Aggregated Profiles (Flexibility Distance),28.7740,71.0541,54.1626,56.6864,59.6773,46.6229,54.2097,45.4824,66.4442
Classical Statistics,0.1468,0.2936,0.1349,0.1689,0.1537,0.1598,0.1736,0.0929,0.0915
Flexibility Distance,0.6749,0.6086,0.4814,0.5123,0.4137,0.4321,0.4415,0.2896,0.5970
Per-Condition Evaluation,0.1011,0.5036,0.2526,0.0775,0.0743,0.0922,0.0860,0.0751,0.1838
Reconstruction Log-Likelihood,-1.8265,-1.6458,-1.4018,-1.5879,-1.4248,-1.4545,-1.4375,-0.9814,-1.6933
Reconstruction RMSE,1.5031,1.2537,0.9830,1.1840,1.0059,1.0362,1.0182,0.6399,1.3087
Set-MMD (Permutation Invariant),0.0185,0.2857,0.1332,0.0772,0.0641,0.0778,0.0816,0.0286,0.1411
"TSTR (Train on Synthetic, Test on Real)",1.1883,1.5000,1.2189,1.1953,1.2705,1.1750,1.2018,1.2266,1.2261
Avg MinMax Synthetic Score,0.9840,0.0000,0.5928,0.6956,0.6969,0.7666,0.7100,0.8557,0.3614
Avg MinMax Reconstruction Score,0.0000,0.2249,0.5358,0.3580,0.5764,0.5371,0.5426,1.0000,0.1950

--- Comparing models for phase: aggregated_phase ---

Model Comparison Table (aggregated_phase):
[['FD on Real & Synth Aggregated Profiles', '28.7740', '71.0541', '54.1626', '56.6864', '59.6773', '46.6229', '54.2097', '45.4824', '66.4442'], ['Reconstruction Flexibility Distance (FD)', '0.6749', '0.6086', '0.4814', '0.5123', '0.4137', '0.4321', '0.4415', '0.2896', '0.5970'], ['Reconstruction Log-Likelihood', '-1.8265', '-1.6458', '-1.4018', '-1.5879', '-1.4248', '-1.4545', '-1.4375', '-0.9814', '-1.6933'], ['Reconstruction RMSE', '1.5031', '1.2537', '0.9830', '1.1840', '1.0059', '1.0362', '1.0182', '0.6399', '1.3087'], ['ACF Distribution Match (KS)', '0.0833', '0.8030', '0.1921', '0.0723', '0.0528', '0.0896', '0.0715', '0.0470', '0.4747'], ['Per-Condition Evaluation', '0.1011', '0.5036', '0.2526', '0.0775', '0.0743', '0.0922', '0.0860', '0.0751', '0.1838'], ['Maximum Mean Discrepancy (MMD)', '0.0185', '0.2857', '0.1332', '0.0772', '0.0641', '0.0778', '0.0816', '0.0286', '0.1411'], ['Train on Synthetic, Test on Real (TSTR)', '1.1883', '1.5000', '1.2189', '1.1953', '1.2705', '1.1750', '1.2018', '1.2266', '1.2261'], ['BEST Overall Reconstruction Score', '0.0000', '0.2249', '0.5358', '0.3580', '0.5764', '0.5371', '0.5426', '1.0000', '0.1950'], ['BEST Overall Synthetic Score', '0.9840', '0.0000', '0.5928', '0.6956', '0.6969', '0.7666', '0.7100', '0.8557', '0.3614']]

Table saved to /Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/evaluation_comparison_hpc_runs/aggregated_phase/comparison_table.txt
Plots saved to /Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/evaluation_comparison_hpc_runs/aggregated_phase/metric_comparison_Reconstruction.png
Plots saved to /Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/evaluation_comparison_hpc_runs/aggregated_phase/metric_comparison_Synthetic.png

--- Comparing models for phase: ranked_phase_1 ---

Model Comparison Table (ranked_phase_1):
[['FD on Real & Synth Aggregated Profiles', '28.7740', '71.0541', '54.1626', '56.6864', '59.6773', '46.6229', '54.2097', '45.4824', '66.4442'], ['Reconstruction Flexibility Distance (FD)', '0.6749', '0.6086', '0.4814', '0.5123', '0.4137', '0.4321', '0.4415', '0.2896', '0.5970'], ['Reconstruction Log-Likelihood', '-1.8265', '-1.6458', '-1.4018', '-1.5879', '-1.4248', '-1.4545', '-1.4375', '-0.9814', '-1.6933'], ['Reconstruction RMSE', '1.5031', '1.2537', '0.9830', '1.1840', '1.0059', '1.0362', '1.0182', '0.6399', '1.3087'], ['ACF Distribution Match (KS)', '0.0833', '0.8030', '0.1921', '0.0723', '0.0528', '0.0896', '0.0715', '0.0470', '0.4747'], ['Per-Condition Evaluation', '0.1011', '0.5036', '0.2526', '0.0775', '0.0743', '0.0922', '0.0860', '0.0751', '0.1838'], ['Maximum Mean Discrepancy (MMD)', '0.0185', '0.2857', '0.1332', '0.0772', '0.0641', '0.0778', '0.0816', '0.0286', '0.1411'], ['Train on Synthetic, Test on Real (TSTR)', '1.1883', '1.5000', '1.2189', '1.1953', '1.2705', '1.1750', '1.2018', '1.2266', '1.2261'], ['BEST Overall Reconstruction Score', '0.0000', '0.2249', '0.5358', '0.3580', '0.5764', '0.5371', '0.5426', '1.0000', '0.1950'], ['BEST Overall Synthetic Score', '0.9840', '0.0000', '0.5928', '0.6956', '0.6969', '0.7666', '0.7100', '0.8557', '0.3614']]

Table saved to /Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/evaluation_comparison_hpc_runs/ranked_phase_1/comparison_table.txt
Plots saved to /Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/evaluation_comparison_hpc_runs/ranked_phase_1/metric_comparison_Reconstruction.png
Plots saved to /Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/evaluation_comparison_hpc_runs/ranked_phase_1/metric_comparison_Synthetic.png
Comparison artifacts written to: /Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/evaluation_comparison_hpc_runs

In [ ]:
for model_name in comparator.models_data:
    v = comparator.models_data[model_name]["aggregated_phase"].get("Avg MinMax Synthetic Score")
    print(model_name, v)

#### 3-phase

In [91]:
PRIMARY_HIERARCHY_MODEL = PROJECT_ROOT / "models" / "hpc_runs" / "CVAE_20260424_174908_hierarcchy"
SECONDARY_SPLITTER_MODEL = PROJECT_ROOT / "models" / "hpc_runs" / "3-phase" / "HierarchicalSplitter_20260426_182151"

MODEL_RUNS_TO_EVAL = [
    "SetGuideVAE_20260426_180021",
    "DiffusionModel_20260426_182935",
    "AverageBaselineModel_20260426_185808",
    "QuantileBaselineModel_20260426_190605",
]

model_paths = [
    str(HPC_RUNS_DIR_PHASED / name)
    for name in MODEL_RUNS_TO_EVAL
]

model_names = [
    "SetGuideVAE",
    "Diffusion",
    "Avg Baseline",
    "Quantile Baseline",
]

secondary_model_paths = [None] * len(model_paths)

# Add hierarchy model: primary = aggregate CVAE, secondary = splitter
model_paths.append(str(PRIMARY_HIERARCHY_MODEL))
model_names.append("GUIDE-VAE-Hierarchy")
secondary_model_paths.append(str(SECONDARY_SPLITTER_MODEL))

In [92]:
secondary_model_paths = []

for model_name in MODEL_RUNS_TO_EVAL:
    if model_name == "HierarchicalSplitter_20260426_182151":
        secondary_model_paths.append(
            str(HPC_RUNS_DIR_PHASED / "HierarchicalSplitter_20260426_182151")
        )
    else:
        secondary_model_paths.append(None)

In [96]:
results = compare_models.compare_models(
    model_paths=model_paths,
    model_names=model_names,
    secondary_model_paths=secondary_model_paths,
    data_dir="/Volumes/USB/raw_profiles",
    num_samples=100,
    output_dir=str(comparison_output_dir),
    phased=True,
    recompute=True,
)

Evaluating model: SetGuideVAE

AttributeError: module 'torch.mps' has no attribute 'current_device'

In [ ]:
import importlib
import pandas as pd
import evaluation.compare_models as compare_models

importlib.reload(compare_models)

ModelComparator = compare_models.PhasedModelComparator

comparison_output_dir = PROJECT_ROOT / "evaluation_comparison_hpc_runs_3phase"
comparator = ModelComparator(output_dir=str(comparison_output_dir))

DISPLAY_MODEL_NAMES = {
    "AutoRegressiveTransformerVAE_20260426_184212": "ART-VAE",
    "AverageBaselineModel_20260426_185808": "Avg Baseline",
    "DiffusionModel_20260426_182935": "Diffusion",
    "HierarchicalSplitter_20260426_182151": "Hierarchical Splitter",
    "QuantileBaselineModel_20260426_190605": "Quantile Baseline",
    "SetGuideVAE_20260426_180021": "SetGuideVAE",
}

added = []

for model_name in MODEL_RUNS_PHASED:
    model_dir = HPC_RUNS_DIR_PHASED / model_name
    eval_json = model_dir / "aggregated_phase_eval" / "eval_results.json"

    if eval_json.exists():
        display_name = DISPLAY_MODEL_NAMES.get(model_name, model_name)
        comparator.add_model(display_name, str(model_dir))
        added.append(display_name)
    else:
        print(f"Skipping {model_name}: eval results not found at {eval_json}")


if not added:
    print("No eval result files found. Run model cells first.")
else:
    print(f"Comparing {len(added)} models...")
    print("Legend names:", ", ".join(added))

    # Compute averages before making notebook table
    comparator._compute_averages("aggregated_phase")

    # Build readable notebook table
    all_metrics = sorted({
        metric
        for model_name in added
        for metric, value in comparator.models_data[model_name]["aggregated_phase"].items()
        if isinstance(value, (int, float))
    })

    # Put summary scores last
    preferred_last = [
        "Avg MinMax Synthetic Score",
        "Avg MinMax Reconstruction Score",
        "BEST overall synthetic score",
        "BEST overall reconstruction score",
    ]

    non_summary = [m for m in all_metrics if m not in preferred_last]
    summary = [m for m in preferred_last if m in all_metrics]
    all_metrics = non_summary + summary

    table_df = pd.DataFrame(index=all_metrics, columns=added, dtype=float)

    for model_name in added:
        metrics = comparator.models_data[model_name]["aggregated_phase"]
        for metric_name in all_metrics:
            metric_val = metrics.get(metric_name)
            if isinstance(metric_val, (int, float)):
                table_df.loc[metric_name, model_name] = metric_val

    table_df.index.name = "Metric"

    print("\nReadable model comparison table:")
    display(table_df.round(4))

    comparator.compare()

    print(f"Comparison artifacts written to: {comparison_output_dir}")

Comparing 5 models...
Legend names: ART-VAE, Avg Baseline, Diffusion, Quantile Baseline, SetGuideVAE

Readable model comparison table:

,ART-VAE,Avg Baseline,Diffusion,Quantile Baseline,SetGuideVAE
Metric,,,,,
ACF Distribution Match (KS),0.1897,0.8923,0.2654,0.3622,0.2467
Aggregated Profiles (Flexibility Distance),25.2479,68.0800,59.0374,46.1820,50.1161
Classical Statistics,0.2177,0.1745,0.2560,0.2195,0.2303
Flexibility Distance,0.7830,0.6360,0.7807,0.6185,0.7837
Per-Condition Evaluation,0.1623,0.5374,0.1694,0.1663,0.1971
Reconstruction Log-Likelihood,-1.8175,-1.5896,-1.9324,-1.6839,-1.9479
Reconstruction RMSE,1.4894,1.1859,1.6708,1.2907,1.6964
Set-MMD (Permutation Invariant),0.0598,0.2148,0.0913,0.1029,0.0806
"TSTR (Train on Synthetic, Test on Real)",0.5895,0.5933,0.5920,0.6124,0.5678
Avg MinMax Synthetic Score,1.0000,0.0000,0.8444,0.7380,0.8922
Avg MinMax Reconstruction Score,0.4434,0.7235,0.0806,0.7607,0.1049

--- Comparing models for phase: aggregated_phase ---

Model Comparison Table (aggregated_phase):
[['Reconstruction Aggregated Profiles (FD)', '25.2479', '68.0800', '59.0374', '46.1820', '50.1161'], ['Reconstruction Flexibility Distance (FD)', '0.7830', '0.6360', '0.7807', '0.6185', '0.7837'], ['Reconstruction Log-Likelihood', '-1.8175', '-1.5896', '-1.9324', '-1.6839', '-1.9479'], ['Reconstruction RMSE', '1.4894', '1.1859', '1.6708', '1.2907', '1.6964'], ['ACF Distribution Match (KS)', '0.1897', '0.8923', '0.2654', '0.3622', '0.2467'], ['Per-Condition Evaluation', '0.1623', '0.5374', '0.1694', '0.1663', '0.1971'], ['Maximum Mean Discrepancy (MMD)', '0.0598', '0.2148', '0.0913', '0.1029', '0.0806'], ['Train on Synthetic, Test on Real (TSTR)', '0.5895', '0.5933', '0.5920', '0.6124', '0.5678'], ['BEST Overall Reconstruction Score', '0.4434', '0.7235', '0.0806', '0.7607', '0.1049'], ['BEST Overall Synthetic Score', '1.0000', '0.0000', '0.8444', '0.7380', '0.8922']]

Table saved to /Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/evaluation_comparison_hpc_runs_3phase/aggregated_phase/comparison_table.txt
Plots saved to /Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/evaluation_comparison_hpc_runs_3phase/aggregated_phase/metric_comparison.png

--- Comparing models for phase: ranked_phase_1 ---

Model Comparison Table (ranked_phase_1):
[['Reconstruction Aggregated Profiles (FD)', '7.8657', '21.5032', '18.7772', '14.1274', '15.7217'], ['Reconstruction Flexibility Distance (FD)', '0.3034', '0.2496', '0.2826', '0.2282', '0.2988'], ['Reconstruction Log-Likelihood', '-0.9086', '-0.6386', '-0.9923', '-0.7084', '-0.9659'], ['Reconstruction RMSE', '0.6002', '0.4582', '0.6527', '0.4887', '0.6355'], ['ACF Distribution Match (KS)', '0.2818', '0.8778', '0.2827', '0.3455', '0.2763'], ['Per-Condition Evaluation', '0.2129', '0.5419', '0.1431', '0.1421', '0.1780'], ['Maximum Mean Discrepancy (MMD)', '0.0993', '0.6022', '0.1238', '0.1666', '0.1421'], ['Train on Synthetic, Test on Real (TSTR)', '0.7488', '0.7903', '0.8332', '0.7847', '0.8067'], ['BEST Overall Reconstruction Score', '0.3766', '0.6790', '0.1190', '0.7968', '0.1620'], ['BEST Overall Synthetic Score', '0.9954', '0.0000', '0.9703', '0.8756', '0.9575']]

Table saved to /Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/evaluation_comparison_hpc_runs_3phase/ranked_phase_1/comparison_table.txt
Plots saved to /Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/evaluation_comparison_hpc_runs_3phase/ranked_phase_1/metric_comparison.png

--- Comparing models for phase: ranked_phase_2 ---

Model Comparison Table (ranked_phase_2):
[['Reconstruction Aggregated Profiles (FD)', '5.1443', '20.6614', '18.1906', '12.7631', '15.0161'], ['Reconstruction Flexibility Distance (FD)', '0.2978', '0.2801', '0.2802', '0.2558', '0.3042'], ['Reconstruction Log-Likelihood', '-0.9247', '-0.7806', '-0.9692', '-0.8450', '-0.9904'], ['Reconstruction RMSE', '0.6100', '0.5281', '0.6378', '0.5603', '0.6514'], ['ACF Distribution Match (KS)', '0.2292', '0.8582', '0.2822', '0.3930', '0.2677'], ['Per-Condition Evaluation', '0.1430', '0.5746', '0.1515', '0.1268', '0.1937'], ['Maximum Mean Discrepancy (MMD)', '0.1385', '0.6023', '0.1362', '0.1434', '0.1557'], ['Train on Synthetic, Test on Real (TSTR)', '1.1852', '1.3415', '0.9794', '1.1826', '1.2377'], ['BEST Overall Reconstruction Score', '0.4456', '0.6247', '0.2167', '0.7353', '0.0910'], ['BEST Overall Synthetic Score', '0.9975', '0.0000', '0.9578', '0.8621', '0.9484']]

Table saved to /Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/evaluation_comparison_hpc_runs_3phase/ranked_phase_2/comparison_table.txt
Plots saved to /Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/evaluation_comparison_hpc_runs_3phase/ranked_phase_2/metric_comparison.png

--- Comparing models for phase: ranked_phase_3 ---

Model Comparison Table (ranked_phase_3):
[['Reconstruction Aggregated Profiles (FD)', '12.8162', '25.9154', '22.8223', '19.2915', '20.0839'], ['Reconstruction Flexibility Distance (FD)', '0.2878', '0.2333', '0.2817', '0.2056', '0.3032'], ['Reconstruction Log-Likelihood', '-0.8999', '-0.5935', '-1.0071', '-0.6526', '-0.9880'], ['Reconstruction RMSE', '0.5949', '0.4380', '0.6623', '0.4631', '0.6495'], ['ACF Distribution Match (KS)', '0.2191', '0.8818', '0.2872', '0.3213', '0.2613'], ['Per-Condition Evaluation', '0.0945', '0.5661', '0.1434', '0.1318', '0.1852'], ['Maximum Mean Discrepancy (MMD)', '0.1092', '0.6578', '0.1400', '0.1544', '0.1548'], ['Train on Synthetic, Test on Real (TSTR)', '0.8899', '0.7479', '0.8347', '0.7825', '0.7871'], ['BEST Overall Reconstruction Score', '0.4294', '0.6790', '0.1141', '0.8128', '0.1372'], ['BEST Overall Synthetic Score', '1.0000', '0.0000', '0.9206', '0.8817', '0.9266']]

Table saved to /Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/evaluation_comparison_hpc_runs_3phase/ranked_phase_3/comparison_table.txt
Plots saved to /Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/evaluation_comparison_hpc_runs_3phase/ranked_phase_3/metric_comparison.png
Comparison artifacts written to: /Users/clarareginekold/Desktop/dtu/THESIS/rasmus-clara-synthetic-data/evaluation_comparison_hpc_runs_3phase